<?php 
/**
 * Magento
 *
 * @author    WakaMage http://www.wakamage.com <cs@wakamage.com>
 * @copyright Copyright (C) 2013 WakaMage. (http://www.wakamage.com)
 *
 */
?>
<!-- iPayMu Logo -->
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/ipaymu/logo-ipaymu.png' ?>" alt="<?php echo Mage::helper('ipaymu')->__('iPayMu Logo') ?>" class="v-middle" />&nbsp;
<a href="<?php echo Mage::getBaseUrl().'ipaymu/whatisipaymu'?>" onclick="javascript:window.open('<?php echo Mage::getBaseUrl().'ipaymu/whatisipaymu'?>','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=400, height=350'); return false;"><?php echo Mage::helper('ipaymu')->__('Apa itu IPAYMU?') ?></a>
<!-- PayPal Logo -->
